server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myTest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: chk@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    #服务发现客户端
eureka:
  instance:
    #向Eureka注册时，是否使用IP地址+端口号作为服务实例的唯一标识。推荐设置为true
    prefer-ip-address: true
    #名称
    appname: wrfx-lcsc
  client:
    #是否将自身的实例信息注册到Eureka服务端
    register-with-eureka: true
    #是否拉取并缓存其他服务注册表副本到本地
    fetch-registry: true
    # eureka client刷新本地缓存时间
    registryFetchIntervalSeconds: 5
    #注册到哪个Eureka服务实例
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  typeAliasesPackage: com.wrfx.lcsc.bean
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true