ribbon:
  # eureka客户端ribbon刷新时间
  ServerListRefreshInterval: 5000

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  freemarker:
    suffix: html
  profiles:
    active: dev
jasypt:
  encryptor:
    password: wrfx_chk_passwork

management:
  server:
    port: 8099
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"



